**Setting up an API call to get historical financial data**  
Connect to 12finance free API to request historical stock data for a stock of my choosing

Plan:
- set up a get request 
    - import requests library
- send request to 12finance API
- recieve data back in JSON format and manipulate into pandas DF
    - extrac

In [1]:
import requests
import pandas as pd
import credentials

#api endpoint 
URL = "https://api.twelvedata.com/time_series?"

#api parameters **EDIT THESE**
api_key = credentials.twelve_data_api_key
interval = '1day'
symbol = 'TSLA'
outputsize = '5000'

#create dictionary of parameters
PARAMS = {'apikey': api_key, 'interval':interval, 'symbol':symbol, 'outputsize':outputsize}

#send get request and save response as response object
r = requests.get(url = URL, params = PARAMS)

#extract data in json format
data = r.json()

#extract time series data
time_series = data['values']



stock = pd.DataFrame(time_series)

stock.head(50)

      datetime       open       high        low      close     volume
0   2023-11-10  210.03000  215.38000  205.69000  214.64999  130994000
1   2023-11-09  219.75000  220.80000  206.67999  209.98000  142110500
2   2023-11-08  223.14999  224.14999  217.64000  222.11000  106584800
3   2023-11-07  219.98000  223.12000  215.72000  222.17999  116900100
4   2023-11-06  223.98000  226.32001  215.00000  219.27000  117335800
5   2023-11-03  221.14999  226.37000  218.39999  219.96001  119281000
6   2023-11-02  212.97000  219.20000  211.45000  218.50999  125987600
7   2023-11-01  204.03999  205.99001  197.85001  205.66000  121661700
8   2023-10-31  196.12000  202.80000  194.07001  200.84000  118068300
9   2023-10-30  209.28000  210.88000  194.67000  197.36000  136448200
10  2023-10-27  210.60001  212.41000  205.77000  207.30000   94881200
11  2023-10-26  211.32001  214.80000  204.88000  205.75999  115112600
12  2023-10-25  215.88000  220.10001  212.20000  212.42000  107065100
13  2023-10-24  216.50000  222.05000  214.11000  216.52000  118231100
14  2023-10-23  210.00000  216.98000  202.50999  212.08000  150683400
15  2023-10-20  217.00999  218.86000  210.42000  211.99001  137734000
16  2023-10-19  225.95000  230.61000  216.78000  220.11000  170772700
17  2023-10-18  252.70000  254.63000  242.08000  242.67999  125147800
18  2023-10-17  250.10001  257.17999  247.08000  254.85001   93562900
19  2023-10-16  250.05000  255.39999  248.48000  253.92000   88917200
20  2023-10-13  258.89999  259.60001  250.22000  251.12000  102073800
21  2023-10-12  262.92001  265.41000  256.63000  258.87000  111508100
22  2023-10-11  266.20001  268.60001  260.89999  262.98999  103706300
23  2023-10-10  257.75000  268.94000  257.64999  263.62000  122656000
24  2023-10-09  255.31000  261.35999  252.05000  259.67001  101377900
25  2023-10-06  253.98000  261.64999  250.64999  260.53000  117947000
26  2023-10-05  260.00000  263.60001  256.25000  260.04999  119159200
27  2023-10-04  248.14000  261.85999  247.60001  261.16000  129721600
28  2023-10-03  248.61000  250.02000  244.45000  246.53000  101985300
29  2023-10-02  244.81000  254.28000  242.62000  251.60001  123810400
30  2023-09-29  250.00000  254.77000  246.35001  250.22000  128346200
31  2023-09-28  240.02000  247.55000  238.64999  246.38000  117058900
32  2023-09-27  244.25999  245.33000  234.58000  240.50000  136597200
33  2023-09-26  242.98000  249.55000  241.66000  244.12000  101993600
34  2023-09-25  243.38000  247.10001  238.31000  246.99001  104636600
35  2023-09-22  257.39999  257.79001  244.48000  244.88000  127524100
36  2023-09-21  257.85001  260.85999  254.21001  255.70000  119531000
37  2023-09-20  267.04001  273.92999  262.45999  262.59000  122514600
38  2023-09-19  264.35001  267.85001  261.20001  266.50000  103704000
39  2023-09-18  271.16000  271.44000  263.76001  265.28000  101543300
40  2023-09-15  277.54999  278.98001  271.00000  274.39001  133422800
41  2023-09-14  271.32001  276.70999  270.42001  276.04001  107709800
42  2023-09-13  270.07001  274.98001  268.10001  271.29999  111673700
43  2023-09-12  270.76001  278.39001  266.60001  267.48001  135999900
44  2023-09-11  264.26999  274.85001  260.60999  273.57999  174667900
45  2023-09-08  251.22000  256.51999  246.67000  248.50000  118367700
46  2023-09-07  245.07001  252.81000  243.27000  251.49001  115312900
47  2023-09-06  255.14000  255.39000  245.06000  251.92000  116959800
48  2023-09-05  245.00000  258.00000  244.86000  256.48999  129469600
49  2023-09-01  257.26001  259.07999  242.00999  245.00999  132272500